firefox_profile: '~/.mozilla/firefox/cp6sgb0s.selenium'
firefox_marionette_port: 2828
firefox_download_dir: '~/.local/share/llmvm/download'
firefox_cookies: '~/.local/share/llmvm/cookies.txt'
smtp_server: 'localhost'
smtp_port: 1025
smtp_username: 'user@domain.com'
smtp_password: ''
cache_directory: '~/.local/share/llmvm/cache'
openai_api_base: 'https://api.openai.com/v1'
openai_model: 'gpt-3.5-turbo-16k-0613'
openai_tools_model: 'gpt-4-0613'
local_openai_api_base: 'http://localhost:8000/v1'
local_model: 'llongorca.gguf'
local_tools_model: 'llongorca.gguf'
local_model_max_tokens: 16385
