firefox_profile: '/home/user/.mozilla/firefox/cp6sgb0s.selenium'
firefox_marionette_port: 2828
firefox_download_dir: '/home/user/llmvm/download'
firefox_cookies: 'cache/cookies.txt'
smtp_server: 'localhost'
smtp_port: 1025
smtp_username: 'blah@blah.net'
smtp_password: 'password'
cache_filename: 'cache/cache.db'
local_openai_api_base: 'http://localhost:8000/v1'
local_openai_api_version: '../models/vicuna.gguf'
