version: "3.8"

services:
  llmvm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SEC_API_KEY: ${SEC_API_KEY}
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
    command: ["python", "-m", "llmvm.server.server"]

